### ISSUE TITLE
Úprava dokumentácie localhost -> container_name

### ISSUE THREAD

**Issue by suweb** [contributte/elastica#9]
Ahoj, dosť dlho som riešil to ako správne nakonfigurovať balíček, respektíve projekt mi beží v docker prostredi a tam je rozdiel čo zadávaš ako **host**. Docker riešim krátko a fakt by pomohla myslím aj ostatným poznámka že ak elasticsearch beží ako container treba host zadať ako container name. Tento názov sa definuje v configurácii dockera ako premenná **container_name: elasticsearch**

Je to maličkosť, možno pre niekoho nepodstatná vec ale aj ked človek googli Couldn't connect to host, Elasticsearch down?
Tak väčšina rieši ping toho url  127.0.0.1:9200 ktorá je cez prehliadač dostupná ale ked to dáš do configu to nefunguje.

**Comment by f3l1x** [comment]
Ahoj. Diky za feedback. Muzes pripravit PR?
